Mhryb/tdi 49704 fix tdit4866 http client die on error true status 500
Talend/tuj pull request #1046
Opened 2023-04-27 09:36 UTC by mhryb

2023-04-27 15:11 UTC, dmytro-sylaiev requested changes
Please activate back the tMysqlOutput

2023-04-27 15:11 UTC, dmytro-sylaiev commented on tuj/java/Internet/TDIT4866_HttpClient_DieOnError_true_Status_500/process/TDIT4866_HttpClient_DieOnError_true_Status_500_0.1.item
> +    <elementParameter field="CHECK" name="ACTIVATE" value="false"/>
see a pb here, please activate this component back

2023-04-27 16:53 UTC, mhryb commented on tuj/java/Internet/TDIT4866_HttpClient_DieOnError_true_Status_500/process/TDIT4866_HttpClient_DieOnError_true_Status_500_0.1.item
> +    <elementParameter field="CHECK" name="ACTIVATE" value="false"/>
Thank you for the notice! I fixed

2023-04-28 14:45 UTC, dmytro-sylaiev approved these changes
LGTM

2023-05-04 13:48 UTC, merged